// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDSc1GIHQNtG30DtvdvypnxPKpiYChHU4',
    appId: '1:131918933728:web:64745c25e7c6b4dfb56a85',
    messagingSenderId: '131918933728',
    projectId: 'advert-4dbe3',
    authDomain: 'advert-4dbe3.firebaseapp.com',
    storageBucket: 'advert-4dbe3.appspot.com',
    measurementId: 'G-8099B59QF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdf7SKFbzwFSXR0s0WdsqsGyKb4BzOnOs',
    appId: '1:131918933728:android:4f000c5d66d4f457b56a85',
    messagingSenderId: '131918933728',
    projectId: 'advert-4dbe3',
    storageBucket: 'advert-4dbe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkn0E15x2HVBLaCPE4_xPSIApYDl6YCxo',
    appId: '1:131918933728:ios:01e4e50e00130a3fb56a85',
    messagingSenderId: '131918933728',
    projectId: 'advert-4dbe3',
    storageBucket: 'advert-4dbe3.appspot.com',
    iosClientId: '131918933728-8bf2dav2dvrc19ms8l0oa6l4avtmojom.apps.googleusercontent.com',
    iosBundleId: 'com.example.advert',
  );
}
